artifacta_roots: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url : https://github.com/Mudassir4545/End-to-End-ML-Project/raw/main/WineQT.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion